### ISSUE TITLE
Issue with email @UTHPortal-server

### ISSUE THREAD

**Issue by pcmitsis** [VolosHack/UTHPortal-server#6]
Καλησπέρα παίδες και μπράβο για το εγχείρημα αρκετά καλή δουλειά.

I was looking at the source code of the server side of your application and I saw that you are using a gmail account to access emails using the username and the password in plain text. I tried to log in with that account but I could not because google got suspicious due to my current ISP :smiley: . Anyway as I can not implement a patch I am sending you guys this [url](http://stackoverflow.com/questions/9134491/access-gmail-imap-with-oauth-2-0-access-token) it will help you keep the functionality that you already have without having the password plain text for some malicious user.

**Comment by paraschas** [comment]
Γεια σου Παναγιώτη! Ευχαριστούμε για το issue report και για τη λύση που προτείνεις.

**Comment by pcmitsis** [comment]
Τίποτα ρε άλλωστε τι δικτυάς θα ήμουν αν δεν βοηθούσα :smiley: Θα έκανα κατευθείαν pull request αλλά λόγο του ότι δεν έχω έρθει ποτέ σε κάνενα meeting δεν ξέρω πως να τεστάρω ότι θα δούλευε όπως θα θέλατε. Ίσως σε κάποιο meeting αργότερα να γίνει καλύτερο documentation. Γενικά έχω όρεξη για coding οπότε αν είναι προσθεσέ με στο organization να βλέπω και να συμβάλλω όσο μπορώ!

**Comment by paraschas** [comment]
Η αλήθεια είναι ότι κι εγώ έχω καιρό να ασχοληθώ με το project οπότε πρέπει να μιλήσω με τον @kkanellis για να κάνω αλλαγές (εκτός αν το ξεπετάξει αυτός όταν το δει :P

+ you've been added to the org!

**Comment by kkanellis** [comment]
Βασικά επειδή το project έχει ξαναγραφτεί ολοκληρωτικά, δεν νομίζω πως έχει νοημα οποιαδήποτε αλλαγή σε αυτο το repo. Πολυ σύντομα θα ανοίξει το άλλο repo που θα έχουν νοημα τα contributions :)

**Comment by paraschas** [comment]
Μπράβο Κώστα! Θυμάμαι που μου είπες ότι σκεφτόσουν να κάνεις ένα rewrite αλλά δεν ήξερα ότι το είχες ξεκινήσει. Περιμένω να βγάλεις τη beta να δω τι έκανες!
